-- 1. Create the books table
CREATE TABLE IF NOT EXISTS books (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  author text NOT NULL,
  status text NOT NULL DEFAULT 'want',
  icon text NOT NULL DEFAULT '📚',
  theme text NOT NULL DEFAULT 'theme-wine',
  genres text[] NOT NULL DEFAULT '{}',
  tags text[] NOT NULL DEFAULT '{}',
  note text,
  pages integer NOT NULL DEFAULT 100,
  similar text[] NOT NULL DEFAULT '{}',
  custom_cover text,
  current_page integer NOT NULL DEFAULT 0,
  is_hidden boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE books ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (anonymous access for reading/writing/deleting/updating)
-- Note: In a production environment, you might restrict these using Supabase Auth,
-- but since this is a private passcode-protected site, we will configure simple public access policies.
CREATE POLICY "Enable read access for all users" ON books FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON books FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON books FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON books FOR DELETE USING (true);

-- 2. Insert all 38 default books
INSERT INTO books (id, title, author, status, icon, theme, genres, tags, note, pages, similar, current_page, is_hidden, is_deleted) VALUES
(1, 'It Ends With Us', 'Colleen Hoover', 'read', '🌻', 'theme-rose', ARRAY['romance', 'literary'], ARRAY['Contemporary Romance', 'Emotional', 'Powerful'], 'One of those books that breaks you open and puts you back together differently.', 384, ARRAY['Ugly Love', 'November 9', 'Reminders of Him'], 384, false, false),
(2, 'A Thousand Splendid Suns', 'Khaled Hosseini', 'read', '🌙', 'theme-navy', ARRAY['literary'], ARRAY['Historical Fiction', 'Heartbreaking', 'Beautiful'], 'A testament to the resilience of women — a book that will never leave you.', 432, ARRAY['The Kite Runner', 'And the Mountains Echoed', 'Pachinko'], 432, false, false),
(3, 'Ugly Love', 'Colleen Hoover', 'read', '💔', 'theme-wine', ARRAY['romance'], ARRAY['Romance', 'Angst', 'Contemporary'], 'The kind of love that hurts beautifully. Classic CoHo.', 322, ARRAY['It Ends With Us', 'November 9', 'People We Meet on Vacation'], 322, false, false),
(4, 'Can Love Happen Twice?', 'Ravinder Singh', 'read', '🎸', 'theme-plum', ARRAY['romance', 'literary'], ARRAY['Indian Romance', 'Sequel', 'Emotional'], 'A desi love story with a heart full of hope and heartbreak.', 240, ARRAY['I Too Had a Love Story', 'Like It Happened Yesterday'], 240, false, false),
(5, 'Beach Read', 'Emily Henry', 'read', '🏖️', 'theme-amber', ARRAY['romance'], ARRAY['Contemporary Romance', 'Witty', 'Writers'], 'Enemies-to-lovers with a summery soul. Perfect.', 368, ARRAY['People We Meet on Vacation', 'Happy Place', 'Book Lovers'], 368, false, false),
(6, 'Do Epic Shit', 'Ankur Warikoo', 'read', '🚀', 'theme-teal', ARRAY['self-help'], ARRAY['Self-Help', 'Motivational', 'Indian Author'], 'Raw, honest advice without the fluff. Loved the directness.', 224, ARRAY['Get Epic Shit Done', 'Karma', 'The Psychology of Money'], 224, false, false),
(7, 'Shatter Me (Series)', 'Tahereh Mafi', 'read', '💫', 'theme-plum', ARRAY['romance', 'literary'], ARRAY['YA Fantasy', 'Romance', 'Dystopian', 'Series'], 'The prose! The prose!! Juliette''s journey from broken to powerful is everything.', 338, ARRAY['Red Queen', 'An Ember in the Ashes', 'The Cruel Prince'], 338, false, false),
(8, 'The Inheritance Games', 'Jennifer Lynn Barnes', 'read', '🎴', 'theme-navy', ARRAY['thriller'], ARRAY['Mystery', 'YA Thriller', 'Puzzles', 'Series'], 'A treasure-hunt mystery that''s absolutely impossible to put down.', 384, ARRAY['One of Us Is Lying', 'A Good Girl''s Guide to Murder', 'The Naturals'], 384, false, false),
(9, 'The American Roommate Experiment', 'Elena Armas', 'read', '🏠', 'theme-rose', ARRAY['romance'], ARRAY['Romance', 'Roommates', 'Spicy', 'Spanish Author'], 'Lucas Martín is a whole character — the date experiments had me swooning.', 419, ARRAY['The Spanish Love Deception', 'Happy Place', 'Book Lovers'], 419, false, false),
(10, '101 Essays That''ll Change the Way You Think', 'Brianna Wiest', 'reading', '🧠', 'theme-forest', ARRAY['self-help'], ARRAY['Essays', 'Philosophy', 'Self-Growth'], 'Still reading — each essay is a tiny earthquake in the mind. ✨', 358, ARRAY['The Mountain Is You', 'I Am the Hero of My Own Life'], 100, false, false),
(11, 'The Silent Patient', 'Alex Michaelides', 'read', '🎭', 'theme-wine', ARRAY['thriller'], ARRAY['Psychological Thriller', 'Twist Ending', 'Dark'], 'That ending! Completely shattered and re-assembled her.', 336, ARRAY['The Woman in the Window', 'Behind Closed Doors', 'Verity'], 336, false, false),
(12, 'A Good Girl''s Guide to Murder', 'Holly Jackson', 'read', '🔍', 'theme-navy', ARRAY['thriller'], ARRAY['Mystery', 'YA', 'True Crime', 'Series'], 'Pip is the detective we all deserved. This series is perfect.', 400, ARRAY['Good Girl Bad Blood', 'As Good as Dead', 'The Inheritance Games'], 400, false, false),
(13, 'As Good as Dead', 'Holly Jackson', 'read', '💀', 'theme-wine', ARRAY['thriller'], ARRAY['Mystery', 'YA', 'Finale', 'Dark'], 'The trilogy closer that didn''t hold back. Pip''s final case — dark and brilliant.', 480, ARRAY['A Good Girl''s Guide to Murder', 'Good Girl Bad Blood', 'Killing Eve'], 480, false, false),
(14, 'Good Girl Bad Blood (Series)', 'Holly Jackson', 'read', '🩸', 'theme-wine', ARRAY['thriller'], ARRAY['Mystery', 'YA', 'True Crime', 'Series of 3'], 'Pip Fitz-Amobi''s full trilogy — three books, zero disappointments.', 390, ARRAY['The Inheritance Games', 'The Silent Patient', 'One of Us Is Lying'], 390, false, false),
(15, 'The Housemaid', 'Freida McFadden', 'read', '🏚️', 'theme-brown', ARRAY['thriller'], ARRAY['Psychological Thriller', 'Domestic Suspense', 'Twist'], 'Every chapter made me trust and distrust everyone differently. Brilliant.', 336, ARRAY['Behind Closed Doors', 'The Au Pair', 'Maid'], 336, false, false),
(16, 'Heaven', 'Mieko Kawakami', 'read', '🕊️', 'theme-navy', ARRAY['literary'], ARRAY['Japanese Literature', 'Coming of Age', 'Bullying', 'Philosophical'], 'Quiet, devastating, profound. Japanese literature has a way of whispering loudly.', 192, ARRAY['Convenience Store Woman', 'Ms Ice Sandwich', 'Before the Coffee Gets Cold'], 192, false, false),
(17, 'The Alchemist', 'Paulo Coelho', 'read', '⚗️', 'theme-amber', ARRAY['self-help', 'literary'], ARRAY['Philosophical Fiction', 'Journey', 'Inspirational'], 'A story about following your Personal Legend. Timeless.', 197, ARRAY['Siddhartha', 'The Prophet', 'Jonathan Livingston Seagull'], 197, false, false),
(18, 'The Love Hypothesis', 'Ali Hazelwood', 'read', '🔬', 'theme-teal', ARRAY['romance'], ARRAY['STEM Romance', 'Academia', 'Fake Dating', 'Relatable'], 'STEM girl romance — she said she can relate a little 😊 The academic setting is chef''s kiss.', 384, ARRAY['Not in Love', 'Check & Mate', 'On the Same Page'], 384, false, false),
(19, 'The Secret', 'Rhonda Byrne', 'read', '🌟', 'theme-amber', ARRAY['self-help'], ARRAY['Law of Attraction', 'Manifestation', 'Self-Help'], 'Read it for manifestation. The universe says yes! ✨', 198, ARRAY['The Power', 'Ask and It Is Given', 'You Are a Badass'], 198, false, false),
(20, 'As Long as Lemon Trees Grow', 'Zoulfa Katouh', 'read', '🍋', 'theme-sage', ARRAY['romance', 'literary'], ARRAY['Syrian Literature', 'War Romance', 'Beautiful', 'Debut'], 'A debut novel that reads like a love poem wrapped in a war cry.', 368, ARRAY['The Kite Runner', 'We Need New Names', 'Girls of Riyadh'], 368, false, false),
(21, 'Normal People', 'Sally Rooney', 'reading', '🫂', 'theme-forest', ARRAY['literary', 'romance'], ARRAY['Literary Fiction', 'Irish', 'Complex Relationships', 'Currently Reading'], 'Currently reading / can''t quite get through — Connell and Marianne''s orbit is compelling.', 273, ARRAY['Conversations with Friends', 'Beautiful World Where Are You', 'Daisy Jones'], 150, false, false),
(22, 'Master of the Game', 'Sidney Sheldon', 'read', '♟️', 'theme-brown', ARRAY['thriller', 'literary'], ARRAY['Saga', 'Generational', 'Diamonds', 'Iconic'], 'Sidney Sheldon at his absolute best — a multi-generational power saga.', 607, ARRAY['Rage of Angels', 'If Tomorrow Comes', 'The Other Side of Midnight'], 607, false, false),
(23, 'Rage of Angels', 'Sidney Sheldon', 'slump', '⚡', 'theme-wine', ARRAY['thriller', 'literary'], ARRAY['Legal Thriller', 'Romance', 'Reading Slump', 'Iconic'], 'In a reading slump with this — but Jennifer Parker is worth coming back to!', 504, ARRAY['Master of the Game', 'Bloodline', 'Mistral''s Daughter'], 200, false, false),
(24, 'Kasap', 'Hindi Literature', 'read', '🪔', 'theme-brown', ARRAY['hindi', 'literary'], ARRAY['Hindi Literature', 'Indian', 'Regional'], 'Hindi literature that roots you deeply in culture and story.', 280, ARRAY['Gunaho Ka Devata', 'Nirmala', 'Gaban'], 280, false, false),
(25, 'Gunaho Ka Devata', 'Dharamvir Bharati', 'read', '🌺', 'theme-rose', ARRAY['hindi', 'romance', 'literary'], ARRAY['Hindi Classic', 'Love Story', 'Iconic', 'Poetic'], 'Chandrakanta aur Sudha ki kahani — Hindi literature ka yeh novel dil ko chhu leta hai.', 296, ARRAY['Nirmala', 'Mrignayanee', 'Raag Darbari'], 296, false, false),
(26, 'The Hidden Hindu', 'Akshat Gupta', 'read', '🕉️', 'theme-amber', ARRAY['literary', 'self-help'], ARRAY['Indian Mythology', 'Thriller', 'Spiritual', 'Series'], 'Mythology meets thriller — Indian storytelling at its most epic.', 316, ARRAY['The Immortals of Meluha', 'Rise of the Argonauts', 'Ramayana'], 316, false, false),
(27, 'Fifty Shades of Grey', 'E.L. James', 'read', '🎀', 'theme-plum', ARRAY['romance'], ARRAY['Dark Romance', 'Contemporary', 'Adult'], 'Ana and Christian''s complicated world — the book that started many readers'' dark romance era.', 514, ARRAY['Haunting Adeline', 'Twisted Love', 'Beautiful Disaster'], 514, false, false),
(28, 'Luv Shuv in New York', 'Indian Author', 'read', '🗽', 'theme-teal', ARRAY['romance', 'literary'], ARRAY['Indian Author', 'NRI Romance', 'Contemporary', 'Desi'], 'A desi love story abroad — the best of two worlds.', 270, ARRAY['Can Love Happen Twice?', '2 States', 'I Too Had a Love Story'], 270, false, false),
(29, 'White Nights', 'Fyodor Dostoevsky', 'read', '🌃', 'theme-navy', ARRAY['literary'], ARRAY['Russian Literature', 'Classic', 'Novella', 'Romantic'], 'Four nights of longing in St. Petersburg. Dostoevsky''s gentlest masterpiece.', 96, ARRAY['The Idiot', 'Crime and Punishment', 'Notes from Underground'], 96, false, false),
(30, 'Metamorphosis', 'Franz Kafka', 'read', '🪲', 'theme-forest', ARRAY['literary'], ARRAY['Absurdism', 'Classic', 'Novella', 'Existential'], 'Gregor Samsa waking up as a bug — Kafka''s weird, perfect metaphor for alienation.', 96, ARRAY['The Trial', 'The Castle', 'In the Penal Colony'], 96, false, false),
(31, 'The Predator', 'Various', 'read', '🦅', 'theme-brown', ARRAY['thriller'], ARRAY['Thriller', 'Dark', 'Suspense'], 'Dark and gripping — exactly the kind of thriller that keeps the night going.', 320, ARRAY['The Housemaid', 'Behind Closed Doors', 'Gone Girl'], 320, false, false),
(32, 'Haunting Adeline', 'H.D. Carlton', 'reading', '🕯️', 'theme-wine', ARRAY['romance', 'thriller'], ARRAY['Dark Romance', 'Stalker Romance', 'Dark Fantasy', 'Haven''t finished'], 'Dark fantasies — she hasn''t read it fully but the aesthetic is *everything*.', 580, ARRAY['Twisted Love', 'Twisted Hate', 'Icebreaker'], 150, false, false),
(33, 'I Want to Die But I Want to Eat Tteokbokki', 'Baek Se Hee', 'read', '🍢', 'theme-teal', ARRAY['literary', 'self-help'], ARRAY['Korean', 'Therapy', 'Mental Health', 'Essay'], 'Like a therapy session in a book — raw, honest, oddly comforting.', 192, ARRAY['The Midnight Library', 'Everything is F*cked', 'How to Stop Feeling Like Sh*t'], 192, false, false),
(34, 'The Let Them Theory', 'Mel Robbins', 'read', '🦋', 'theme-sage', ARRAY['self-help'], ARRAY['Self-Help', 'Mindset', 'Liberation', 'Boundaries'], 'Let them. Let them. Let them. Changed so much about how I think about others'' actions.', 272, ARRAY['The High 5 Habit', 'Atomic Habits', 'Set Boundaries Find Peace'], 272, false, false),
(35, 'Better Than the Movies', 'Lynn Painter', 'read', '🎬', 'theme-rose', ARRAY['romance'], ARRAY['YA Romance', 'Movie References', 'Enemies-to-Lovers', 'Cute'], 'A love story for people who grew up watching rom-coms. So, so cute.', 385, ARRAY['The Statistical Probability of Love', 'To All the Boys I''ve Loved Before', 'P.S. I Still Love You'], 385, false, false),
(36, 'The Seven Year Slip', 'Ashley Poston', 'read', '⏳', 'theme-amber', ARRAY['romance', 'literary'], ARRAY['Time Travel Romance', 'Magical Realism', 'Grief', 'Cozy'], 'A time-slip romance that handles grief and love with such delicate hands.', 352, ARRAY['The Dead and the Dark', 'In Other Lands', 'Beach Read'], 352, false, false),
(37, 'Autobiography of a Yogi', 'Paramahansa Yogananda', 'read', '🧘', 'theme-forest', ARRAY['literary', 'self-help'], ARRAY['Spiritual', 'Autobiography', 'Virat Kohli', 'Steve Jobs', 'Transcendent'], 'Virat Kohli + Steve Jobs both read this. A spiritual journey unlike any other.', 592, ARRAY['Be Here Now', 'The Power of Now', 'Siddhartha'], 592, false, false),
(38, 'A Place Called Here', 'Cecelia Ahern', 'read', '🚪', 'theme-plum', ARRAY['literary', 'romance'], ARRAY['Magical Realism', 'Missing Things', 'Irish', 'Whimsical'], 'A world where all lost things go — a whimsical, touching, beautiful idea.', 374, ARRAY['P.S. I Love You', 'Thanks for the Memories', 'Love Rosie'], 374, false, false);

-- Adjust the sequence value to restart at 39
SELECT setval(pg_get_serial_sequence('books', 'id'), coalesce(max(id), 0) + 1, false) FROM books;
