export const DEFAULT_BOOKS = [
  {
    id: 1,
    title: "It Ends With Us",
    author: "Colleen Hoover",
    status: "read",
    icon: "🌻",
    theme: "theme-rose",
    genres: ["romance", "literary"],
    tags: ["Contemporary Romance", "Emotional", "Powerful"],
    note: "One of those books that breaks you open and puts you back together differently.",
    pages: 384,
    similar: ["Ugly Love", "November 9", "Reminders of Him"],
    current_page: 384,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 2,
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    status: "read",
    icon: "🌙",
    theme: "theme-navy",
    genres: ["literary"],
    tags: ["Historical Fiction", "Heartbreaking", "Beautiful"],
    note: "A testament to the resilience of women — a book that will never leave you.",
    pages: 432,
    similar: ["The Kite Runner", "And the Mountains Echoed", "Pachinko"],
    current_page: 432,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 3,
    title: "Ugly Love",
    author: "Colleen Hoover",
    status: "read",
    icon: "💔",
    theme: "theme-wine",
    genres: ["romance"],
    tags: ["Romance", "Angst", "Contemporary"],
    note: "The kind of love that hurts beautifully. Classic CoHo.",
    pages: 322,
    similar: ["It Ends With Us", "November 9", "People We Meet on Vacation"],
    current_page: 322,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 4,
    title: "Can Love Happen Twice?",
    author: "Ravinder Singh",
    status: "read",
    icon: "🎸",
    theme: "theme-plum",
    genres: ["romance", "literary"],
    tags: ["Indian Romance", "Sequel", "Emotional"],
    note: "A desi love story with a heart full of hope and heartbreak.",
    pages: 240,
    similar: ["I Too Had a Love Story", "Like It Happened Yesterday"],
    current_page: 240,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 5,
    title: "Beach Read",
    author: "Emily Henry",
    status: "read",
    icon: "🏖️",
    theme: "theme-amber",
    genres: ["romance"],
    tags: ["Contemporary Romance", "Witty", "Writers"],
    note: "Enemies-to-lovers with a summery soul. Perfect.",
    pages: 368,
    similar: ["People We Meet on Vacation", "Happy Place", "Book Lovers"],
    current_page: 368,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 6,
    title: "Do Epic Shit",
    author: "Ankur Warikoo",
    status: "read",
    icon: "🚀",
    theme: "theme-teal",
    genres: ["self-help"],
    tags: ["Self-Help", "Motivational", "Indian Author"],
    note: "Raw, honest advice without the fluff. Loved the directness.",
    pages: 224,
    similar: ["Get Epic Shit Done", "Karma", "The Psychology of Money"],
    current_page: 224,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 7,
    title: "Shatter Me (Series)",
    author: "Tahereh Mafi",
    status: "read",
    icon: "💫",
    theme: "theme-plum",
    genres: ["romance", "literary"],
    tags: ["YA Fantasy", "Romance", "Dystopian", "Series"],
    note: "The prose! The prose!! Juliette's journey from broken to powerful is everything.",
    pages: 338,
    similar: ["Red Queen", "An Ember in the Ashes", "The Cruel Prince"],
    current_page: 338,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 8,
    title: "The Inheritance Games",
    author: "Jennifer Lynn Barnes",
    status: "read",
    icon: "🎴",
    theme: "theme-navy",
    genres: ["thriller"],
    tags: ["Mystery", "YA Thriller", "Puzzles", "Series"],
    note: "A treasure-hunt mystery that's absolutely impossible to put down.",
    pages: 384,
    similar: ["One of Us Is Lying", "A Good Girl's Guide to Murder", "The Naturals"],
    current_page: 384,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 9,
    title: "The American Roommate Experiment",
    author: "Elena Armas",
    status: "read",
    icon: "🏠",
    theme: "theme-rose",
    genres: ["romance"],
    tags: ["Romance", "Roommates", "Spicy", "Spanish Author"],
    note: "Lucas Martín is a whole character — the date experiments had me swooning.",
    pages: 419,
    similar: ["The Spanish Love Deception", "Happy Place", "Book Lovers"],
    current_page: 419,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 10,
    title: "101 Essays That'll Change the Way You Think",
    author: "Brianna Wiest",
    status: "reading",
    icon: "🧠",
    theme: "theme-forest",
    genres: ["self-help"],
    tags: ["Essays", "Philosophy", "Self-Growth"],
    note: "Still reading — each essay is a tiny earthquake in the mind. ✨",
    pages: 358,
    similar: ["The Mountain Is You", "I Am the Hero of My Own Life"],
    current_page: 100,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 11,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    status: "read",
    icon: "🎭",
    theme: "theme-wine",
    genres: ["thriller"],
    tags: ["Psychological Thriller", "Twist Ending", "Dark"],
    note: "That ending! Completely shattered and re-assembled her.",
    pages: 336,
    similar: ["The Woman in the Window", "Behind Closed Doors", "Verity"],
    current_page: 336,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 12,
    title: "A Good Girl's Guide to Murder",
    author: "Holly Jackson",
    status: "read",
    icon: "🔍",
    theme: "theme-navy",
    genres: ["thriller"],
    tags: ["Mystery", "YA", "True Crime", "Series"],
    note: "Pip is the detective we all deserved. This series is perfect.",
    pages: 400,
    similar: ["Good Girl Bad Blood", "As Good as Dead", "The Inheritance Games"],
    current_page: 400,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 13,
    title: "As Good as Dead",
    author: "Holly Jackson",
    status: "read",
    icon: "💀",
    theme: "theme-wine",
    genres: ["thriller"],
    tags: ["Mystery", "YA", "Finale", "Dark"],
    note: "The trilogy closer that didn't hold back. Pip's final case — dark and brilliant.",
    pages: 480,
    similar: ["A Good Girl's Guide to Murder", "Good Girl Bad Blood", "Killing Eve"],
    current_page: 480,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 14,
    title: "Good Girl Bad Blood (Series)",
    author: "Holly Jackson",
    status: "read",
    icon: "🩸",
    theme: "theme-wine",
    genres: ["thriller"],
    tags: ["Mystery", "YA", "True Crime", "Series of 3"],
    note: "Pip Fitz-Amobi's full trilogy — three books, zero disappointments.",
    pages: 390,
    similar: ["The Inheritance Games", "The Silent Patient", "One of Us Is Lying"],
    current_page: 390,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 15,
    title: "The Housemaid",
    author: "Freida McFadden",
    status: "read",
    icon: "🏚️",
    theme: "theme-brown",
    genres: ["thriller"],
    tags: ["Psychological Thriller", "Domestic Suspense", "Twist"],
    note: "Every chapter made me trust and distrust everyone differently. Brilliant.",
    pages: 336,
    similar: ["Behind Closed Doors", "The Au Pair", "Maid"],
    current_page: 336,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 16,
    title: "Heaven",
    author: "Mieko Kawakami",
    status: "read",
    icon: "🕊️",
    theme: "theme-navy",
    genres: ["literary"],
    tags: ["Japanese Literature", "Coming of Age", "Bullying", "Philosophical"],
    note: "Quiet, devastating, profound. Japanese literature has a way of whispering loudly.",
    pages: 192,
    similar: ["Convenience Store Woman", "Ms Ice Sandwich", "Before the Coffee Gets Cold"],
    current_page: 192,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 17,
    title: "The Alchemist",
    author: "Paulo Coelho",
    status: "read",
    icon: "⚗️",
    theme: "theme-amber",
    genres: ["self-help", "literary"],
    tags: ["Philosophical Fiction", "Journey", "Inspirational"],
    note: "A story about following your Personal Legend. Timeless.",
    pages: 197,
    similar: ["Siddhartha", "The Prophet", "Jonathan Livingston Seagull"],
    current_page: 197,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 18,
    title: "The Love Hypothesis",
    author: "Ali Hazelwood",
    status: "read",
    icon: "🔬",
    theme: "theme-teal",
    genres: ["romance"],
    tags: ["STEM Romance", "Academia", "Fake Dating", "Relatable"],
    note: "STEM girl romance — she said she can relate a little 😊 The academic setting is chef's kiss.",
    pages: 384,
    similar: ["Not in Love", "Check & Mate", "On the Same Page"],
    current_page: 384,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 19,
    title: "The Secret",
    author: "Rhonda Byrne",
    status: "read",
    icon: "🌟",
    theme: "theme-amber",
    genres: ["self-help"],
    tags: ["Law of Attraction", "Manifestation", "Self-Help"],
    note: "Read it for manifestation. The universe says yes! ✨",
    pages: 198,
    similar: ["The Power", "Ask and It Is Given", "You Are a Badass"],
    current_page: 198,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 20,
    title: "As Long as Lemon Trees Grow",
    author: "Zoulfa Katouh",
    status: "read",
    icon: "🍋",
    theme: "theme-sage",
    genres: ["romance", "literary"],
    tags: ["Syrian Literature", "War Romance", "Beautiful", "Debut"],
    note: "A debut novel that reads like a love poem wrapped in a war cry.",
    pages: 368,
    similar: ["The Kite Runner", "We Need New Names", "Girls of Riyadh"],
    current_page: 368,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 21,
    title: "Normal People",
    author: "Sally Rooney",
    status: "reading",
    icon: "🫂",
    theme: "theme-forest",
    genres: ["literary", "romance"],
    tags: ["Literary Fiction", "Irish", "Complex Relationships", "Currently Reading"],
    note: "Currently reading / can't quite get through — Connell and Marianne's orbit is compelling.",
    pages: 273,
    similar: ["Conversations with Friends", "Beautiful World Where Are You", "Daisy Jones"],
    current_page: 150,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 22,
    title: "Master of the Game",
    author: "Sidney Sheldon",
    status: "read",
    icon: "♟️",
    theme: "theme-brown",
    genres: ["thriller", "literary"],
    tags: ["Saga", "Generational", "Diamonds", "Iconic"],
    note: "Sidney Sheldon at his absolute best — a multi-generational power saga.",
    pages: 607,
    similar: ["Rage of Angels", "If Tomorrow Comes", "The Other Side of Midnight"],
    current_page: 607,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 23,
    title: "Rage of Angels",
    author: "Sidney Sheldon",
    status: "slump",
    icon: "⚡",
    theme: "theme-wine",
    genres: ["thriller", "literary"],
    tags: ["Legal Thriller", "Romance", "Reading Slump", "Iconic"],
    note: "In a reading slump with this — but Jennifer Parker is worth coming back to!",
    pages: 504,
    similar: ["Master of the Game", "Bloodline", "Mistral's Daughter"],
    current_page: 200,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 24,
    title: "Kasap",
    author: "Hindi Literature",
    status: "read",
    icon: "🪔",
    theme: "theme-brown",
    genres: ["hindi", "literary"],
    tags: ["Hindi Literature", "Indian", "Regional"],
    note: "Hindi literature that roots you deeply in culture and story.",
    pages: 280,
    similar: ["Gunaho Ka Devata", "Nirmala", "Gaban"],
    current_page: 280,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 25,
    title: "Gunaho Ka Devata",
    author: "Dharamvir Bharati",
    status: "read",
    icon: "🌺",
    theme: "theme-rose",
    genres: ["hindi", "romance", "literary"],
    tags: ["Hindi Classic", "Love Story", "Iconic", "Poetic"],
    note: "Chandrakanta aur Sudha ki kahani — Hindi literature ka yeh novel dil ko chhu leta hai.",
    pages: 296,
    similar: ["Nirmala", "Mrignayanee", "Raag Darbari"],
    current_page: 296,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 26,
    title: "The Hidden Hindu",
    author: "Akshat Gupta",
    status: "read",
    icon: "🕉️",
    theme: "theme-amber",
    genres: ["literary", "self-help"],
    tags: ["Indian Mythology", "Thriller", "Spiritual", "Series"],
    note: "Mythology meets thriller — Indian storytelling at its most epic.",
    pages: 316,
    similar: ["The Immortals of Meluha", "Rise of the Argonauts", "Ramayana"],
    current_page: 316,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 27,
    title: "Fifty Shades of Grey",
    author: "E.L. James",
    status: "read",
    icon: "🎀",
    theme: "theme-plum",
    genres: ["romance"],
    tags: ["Dark Romance", "Contemporary", "Adult"],
    note: "Ana and Christian's complicated world — the book that started many readers' dark romance era.",
    pages: 514,
    similar: ["Haunting Adeline", "Twisted Love", "Beautiful Disaster"],
    current_page: 514,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 28,
    title: "Luv Shuv in New York",
    author: "Indian Author",
    status: "read",
    icon: "🗽",
    theme: "theme-teal",
    genres: ["romance", "literary"],
    tags: ["Indian Author", "NRI Romance", "Contemporary", "Desi"],
    note: "A desi love story abroad — the best of two worlds.",
    pages: 270,
    similar: ["Can Love Happen Twice?", "2 States", "I Too Had a Love Story"],
    current_page: 270,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 29,
    title: "White Nights",
    author: "Fyodor Dostoevsky",
    status: "read",
    icon: "🌃",
    theme: "theme-navy",
    genres: ["literary"],
    tags: ["Russian Literature", "Classic", "Novella", "Romantic"],
    note: "Four nights of longing in St. Petersburg. Dostoevsky's gentlest masterpiece.",
    pages: 96,
    similar: ["The Idiot", "Crime and Punishment", "Notes from Underground"],
    current_page: 96,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 30,
    title: "Metamorphosis",
    author: "Franz Kafka",
    status: "read",
    icon: "🪲",
    theme: "theme-forest",
    genres: ["literary"],
    tags: ["Absurdism", "Classic", "Novella", "Existential"],
    note: "Gregor Samsa waking up as a bug — Kafka's weird, perfect metaphor for alienation.",
    pages: 96,
    similar: ["The Trial", "The Castle", "In the Penal Colony"],
    current_page: 96,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 31,
    title: "The Predator",
    author: "Various",
    status: "read",
    icon: "🦅",
    theme: "theme-brown",
    genres: ["thriller"],
    tags: ["Thriller", "Dark", "Suspense"],
    note: "Dark and gripping — exactly the kind of thriller that keeps the night going.",
    pages: 320,
    similar: ["The Housemaid", "Behind Closed Doors", "Gone Girl"],
    current_page: 320,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 32,
    title: "Haunting Adeline",
    author: "H.D. Carlton",
    status: "reading",
    icon: "🕯️",
    theme: "theme-wine",
    genres: ["romance", "thriller"],
    tags: ["Dark Romance", "Stalker Romance", "Dark Fantasy", "Haven't finished"],
    note: "Dark fantasies — she hasn't read it fully but the aesthetic is *everything*.",
    pages: 580,
    similar: ["Twisted Love", "Twisted Hate", "Icebreaker"],
    current_page: 150,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 33,
    title: "I Want to Die But I Want to Eat Tteokbokki",
    author: "Baek Se Hee",
    status: "read",
    icon: "🍢",
    theme: "theme-teal",
    genres: ["literary", "self-help"],
    tags: ["Korean", "Therapy", "Mental Health", "Essay"],
    note: "Like a therapy session in a book — raw, honest, oddly comforting.",
    pages: 192,
    similar: ["The Midnight Library", "Everything is F*cked", "How to Stop Feeling Like Sh*t"],
    current_page: 192,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 34,
    title: "The Let Them Theory",
    author: "Mel Robbins",
    status: "read",
    icon: "🦋",
    theme: "theme-sage",
    genres: ["self-help"],
    tags: ["Self-Help", "Mindset", "Liberation", "Boundaries"],
    note: "Let them. Let them. Let them. Changed so much about how I think about others' actions.",
    pages: 272,
    similar: ["The High 5 Habit", "Atomic Habits", "Set Boundaries Find Peace"],
    current_page: 272,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 35,
    title: "Better Than the Movies",
    author: "Lynn Painter",
    status: "read",
    icon: "🎬",
    theme: "theme-rose",
    genres: ["romance"],
    tags: ["YA Romance", "Movie References", "Enemies-to-Lovers", "Cute"],
    note: "A love story for people who grew up watching rom-coms. So, so cute.",
    pages: 385,
    similar: ["The Statistical Probability of Love", "To All the Boys I've Loved Before", "P.S. I Still Love You"],
    current_page: 385,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 36,
    title: "The Seven Year Slip",
    author: "Ashley Poston",
    status: "read",
    icon: "⏳",
    theme: "theme-amber",
    genres: ["romance", "literary"],
    tags: ["Time Travel Romance", "Magical Realism", "Grief", "Cozy"],
    note: "A time-slip romance that handles grief and love with such delicate hands.",
    pages: 352,
    similar: ["The Dead and the Dark", "In Other Lands", "Beach Read"],
    current_page: 352,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 37,
    title: "Autobiography of a Yogi",
    author: "Paramahansa Yogananda",
    status: "read",
    icon: "🧘",
    theme: "theme-forest",
    genres: ["literary", "self-help"],
    tags: ["Spiritual", "Autobiography", "Virat Kohli", "Steve Jobs", "Transcendent"],
    note: "Virat Kohli + Steve Jobs both read this. A spiritual journey unlike any other.",
    pages: 592,
    similar: ["Be Here Now", "The Power of Now", "Siddhartha"],
    current_page: 592,
    is_hidden: false,
    is_deleted: false
  },
  {
    id: 38,
    title: "A Place Called Here",
    author: "Cecelia Ahern",
    status: "read",
    icon: "🚪",
    theme: "theme-plum",
    genres: ["literary", "romance"],
    tags: ["Magical Realism", "Missing Things", "Irish", "Whimsical"],
    note: "A world where all lost things go — a whimsical, touching, beautiful idea.",
    pages: 374,
    similar: ["P.S. I Love You", "Thanks for the Memories", "Love Rosie"],
    current_page: 374,
    is_hidden: false,
    is_deleted: false
  }
];
export const EXTRA_RECOMMENDATIONS = {
  romance: [
    "November 9",
    "Reminders of Him",
    "Book Lovers",
    "Happy Place",
    "People We Meet on Vacation",
  ],
  thriller: [
    "Verity",
    "Behind Closed Doors",
    "Gone Girl",
    "One of Us Is Lying",
    "The Woman in the Window",
  ],
  literary: [
    "Pachinko",
    "Conversations with Friends",
    "Daisy Jones & The Six",
    "The Midnight Library",
  ],
  selfhelp: [
    "Atomic Habits",
    "The Mountain Is You",
    "The Psychology of Money",
    "You Are a Badass",
  ],
  hindi: ["Nirmala", "Gaban", "Raag Darbari", "Mrignayanee"],
};
